# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/f0x52/glitch-soc.git";
    rev = "351fc0e12a0be3e6ac8c5c51af561859d36846c2";
    sha256 = "0n9sn4jfv195pwgcj39lbcyipr401h6fqic9h6r1gq6fmshdcnzn";
  };
in applyPatches {
  inherit src;
  patches = [];
}
