# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub
, applyPatches
, patches ? [ ]
,
}:
let
  version = "4.4.1";
in
applyPatches {
  src = fetchFromGitHub {
    owner = "glitch-soc";
    repo = "mastodon";
    rev = "v${version}";
    hash = "sha256-XdfDX4IX1zRhdAHVsIjOc/LzUUlIOn2jQZdxDlfkpjg=";
    passthru = {
      inherit version;
      yarnHash = "sha256-uJ5CborG6I9o1uIKRLaE0eLBqAHQFtpOPqDk7pHpMsI=";
      yarnMissingHashes = ./missing-hashes.json;
    };
  };
  patches = patches ++ [ ];
}
