# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon";
    rev = "513078de7acea9eb3809e04c8b9bfb67f3039d60";
    sha256 = "0asm0ysph85h9hcyvn0mj32mvxpl38nfc78l1dbgjwxpfc7xh052";
  };
in applyPatches {
  inherit src;
  patches = [];
}
