# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon.git";
    rev = "8c56441b4a52f23d4793f35fdf27a815cced0d61";
    sha256 = "0qiajghzzfyqc8wd37kkjh5xrca7lpq2fpqcdxi0d00v0xzr439h";
  };
in applyPatches {
  inherit src;
  patches = [];
}
